{
  "hash": "4ad2a1608015021fa2b6e1717585c665",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"The Contact Quality Decline Held Up Through a Full August\"\ndescription: \"Now that August is complete, a follow-up on hard-hit rate's five-month decline, a still-flat whiff rate, and where home run rate and wOBA landed after their June peak.\"\ndate: 2026-09-03\ncategories: [Baseball]\n---\n\nOur [last post](/posts/baseball/2026-08-11-contact-quality-trend/index.qmd)\nflagged a real trend on a partial August: hard-hit rate falling for four\nstraight months, whiff rate holding flat, and home run rate and wOBA\nboth cooling off two months after peaking in June. We closed by saying\nwe'd check back once the month was actually finished. It is now, and\nthe trend held.\n\n## The season, six complete months\n\n::: {#cell-fetch-monthly-trend .cell execution_count=1}\n``` {.python .cell-code}\nfrom google.cloud import bigquery\n\nclient = bigquery.Client()\n\nmonthly_query = \"\"\"\nSELECT\n  FORMAT_DATE('%Y-%m', CAST(game_date AS DATE)) AS month,\n  COUNT(DISTINCT game_pk) AS games,\n  ROUND(SAFE_DIVIDE(SUM(woba_value), SUM(woba_denom)), 3) AS lg_woba,\n  ROUND(SAFE_DIVIDE(COUNTIF(events = 'strikeout'), COUNTIF(events IS NOT NULL)), 3) AS k_rate,\n  ROUND(SAFE_DIVIDE(COUNTIF(events = 'walk'), COUNTIF(events IS NOT NULL)), 3) AS bb_rate,\n  ROUND(SAFE_DIVIDE(COUNTIF(events = 'home_run'), COUNTIF(events IS NOT NULL)), 4) AS hr_rate,\n  ROUND(SAFE_DIVIDE(COUNTIF(description IN ('swinging_strike', 'swinging_strike_blocked')), COUNTIF(description IS NOT NULL)), 3) AS whiff_rate,\n  ROUND(AVG(launch_speed), 2) AS avg_exit_velo,\n  ROUND(SAFE_DIVIDE(COUNTIF(launch_speed >= 95), COUNTIF(launch_speed IS NOT NULL)), 3) AS hard_hit_rate,\n  ROUND(AVG(IF(pitch_type IN ('FF', 'SI'), release_speed, NULL)), 2) AS avg_fastball_velo\nFROM `maydaystats.mlb_statcast.pitches`\nWHERE game_type = 'R' AND CAST(game_date AS DATE) < '2026-09-01'\nGROUP BY month\nORDER BY month\n\"\"\"\n\nmonthly = client.query(monthly_query).to_dataframe()\nmonthly_tbl = monthly.reset_index(drop=True)\nmonthly_tbl.index += 1\nmonthly_tbl\n```\n\n::: {#fetch-monthly-trend .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>month</th>\n      <th>games</th>\n      <th>lg_woba</th>\n      <th>k_rate</th>\n      <th>bb_rate</th>\n      <th>hr_rate</th>\n      <th>whiff_rate</th>\n      <th>avg_exit_velo</th>\n      <th>hard_hit_rate</th>\n      <th>avg_fastball_velo</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>2026-03</td>\n      <td>76</td>\n      <td>0.317</td>\n      <td>0.244</td>\n      <td>0.095</td>\n      <td>0.0279</td>\n      <td>0.119</td>\n      <td>82.67</td>\n      <td>0.247</td>\n      <td>94.49</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2026-04</td>\n      <td>392</td>\n      <td>0.328</td>\n      <td>0.216</td>\n      <td>0.092</td>\n      <td>0.0281</td>\n      <td>0.106</td>\n      <td>82.67</td>\n      <td>0.249</td>\n      <td>94.29</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2026-05</td>\n      <td>419</td>\n      <td>0.320</td>\n      <td>0.218</td>\n      <td>0.085</td>\n      <td>0.0284</td>\n      <td>0.107</td>\n      <td>82.77</td>\n      <td>0.244</td>\n      <td>94.50</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2026-06</td>\n      <td>394</td>\n      <td>0.334</td>\n      <td>0.222</td>\n      <td>0.083</td>\n      <td>0.0342</td>\n      <td>0.109</td>\n      <td>82.51</td>\n      <td>0.240</td>\n      <td>94.69</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>2026-07</td>\n      <td>371</td>\n      <td>0.327</td>\n      <td>0.222</td>\n      <td>0.082</td>\n      <td>0.0319</td>\n      <td>0.110</td>\n      <td>82.47</td>\n      <td>0.235</td>\n      <td>94.64</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>2026-08</td>\n      <td>417</td>\n      <td>0.323</td>\n      <td>0.217</td>\n      <td>0.086</td>\n      <td>0.0289</td>\n      <td>0.106</td>\n      <td>82.31</td>\n      <td>0.231</td>\n      <td>94.59</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nSeptember has already started, but this post deliberately stops at\nAugust 31. A handful of September games would add more noise than\nsignal to a monthly view, so it's better to close the book on a\ncomplete month than tack on a partial one.\n\n::: {#cell-fig-woba-by-month .cell execution_count=2}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nfig, ax = plt.subplots(figsize=(8, 5))\nax.plot(monthly[\"month\"], monthly[\"lg_woba\"], marker=\"o\", linewidth=2.5, color=\"#2c3e50\")\nax.set_ylabel(\"wOBA\")\nax.set_title(\"League wOBA by Month, 2026\")\nax.spines[[\"top\", \"right\"]].set_visible(False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![League-wide wOBA by month, six complete months](index_files/figure-html/fig-woba-by-month-output-1.png){#fig-woba-by-month width=761 height=470}\n:::\n:::\n\n\nwOBA closed August at .323, its second straight month down from June's\n.334 peak but still above where the season opened in March (.317). The\nclimb-then-cool shape from the last post held up exactly as it looked\non the partial data.\n\n## Hard-hit rate: five months down, not four\n\n::: {#cell-fig-contact-vs-whiff .cell execution_count=3}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(8, 5))\nax.plot(monthly[\"month\"], monthly[\"hard_hit_rate\"], marker=\"o\", linewidth=2.5, color=\"#2c3e50\", label=\"Hard-hit rate\")\nax.plot(monthly[\"month\"], monthly[\"whiff_rate\"], marker=\"o\", linewidth=2.5, color=\"#c0392b\", label=\"Whiff rate\")\nax.set_ylabel(\"Rate\")\nax.set_title(\"Contact Quality Is Still Falling; Whiffs Still Aren't\")\nax.spines[[\"top\", \"right\"]].set_visible(False)\nax.legend(loc=\"upper center\", bbox_to_anchor=(0.5, -0.12), ncol=2, frameon=False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Hard-hit rate vs. whiff rate, by month](index_files/figure-html/fig-contact-vs-whiff-output-1.png){#fig-contact-vs-whiff width=760 height=468}\n:::\n:::\n\n\nThe partial August read in the last post had hard-hit rate at .229\nacross 124 games. The completed month landed at .231. A full slate of\n417 games told almost exactly the same story as the smaller sample\ndid. That makes five straight months of decline from April's .249\npeak: .244 in May, .240 in June, .235 in July, and .231 in August.\nEvery month since April has come in lower than the one before it.\nAverage exit velocity shows the same pattern: it fell from May's\n82.77 mph peak to 82.31 in August, the lowest point of the year.\n\nWhiff rate is exactly where it's been all season: .106 in August,\ninside the same .106 to .110 band it's held since April. After five\nmonths of softer contact, hitters still aren't missing the ball any\nmore often than they were in the spring. Whatever's driving this\nisn't strikeouts.\n\n## Home runs and wOBA: three months down from the June peak\n\n::: {#cell-fig-hr-rate-by-month .cell execution_count=4}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(8, 5))\nax.bar(monthly[\"month\"], monthly[\"hr_rate\"], color=\"#2c3e50\")\nax.set_xlabel(\"Month\")\nax.set_ylabel(\"Home runs per plate appearance\")\nax.set_title(\"League HR Rate by Month, 2026\")\nax.spines[[\"top\", \"right\"]].set_visible(False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![League-wide home run rate per plate appearance, by month](index_files/figure-html/fig-hr-rate-by-month-output-1.png){#fig-hr-rate-by-month width=760 height=470}\n:::\n:::\n\n\nHome run rate peaked in June at .0342 and has fallen every month\nsince, .0319 in July and .0289 in August. That's essentially back to\nwhere it started in April and May (.0281 and .0284). It's also three\nstraight months of decline following the June high, one more confirmed\nmonth than we had last time.\n\nThe lag we flagged before still holds up too: hard-hit rate started\nsliding in May, a full month before home run rate and wOBA turned over\nin July. Warmer summer air can carry a fly ball a little further,\nwhich was our explanation for the spring climb, and that could\nplausibly explain why production kept rising for a while even as\ncontact quality was already softening underneath it, before finally\ncatching down in July. That's a hypothesis, not something this data\ncan confirm outright. But the shape of six complete months fits it\nbetter than assuming contact quality and production should always\nmove together.\n\n## What this doesn't say\n\nFive months in one season is a real pattern, not a coin flip, though\nit's still a single season rather than a multi-year baseline. Pitching\nisn't the explanation either: fastball velocity held essentially flat\nall year, between 94.3 and 94.7 mph, so this isn't pitchers throwing\nsofter, and as covered above, it isn't a strikeout story. What's\nactually driving the decline, a real shift in swing decisions,\nballpark and weather effects fading as summer turns to fall, or\nsomething else entirely, is more than this data alone can answer. It\ncan describe the shape of the trend, not explain the cause behind it.\nSeptember's early games will start adding to that picture soon enough.\n\n::: {.callout-note}\nThis post uses Quarto's frozen execution (`freeze: auto`): the numbers\nabove reflect `mlb_statcast.pitches` as of whenever this was last\nrendered locally, not a live query on every page load. The query is\nexplicitly bounded to games before September 1, so a re-render won't\npull in September data even after more of it exists.\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}