{
  "hash": "226f656377943eb3b6b45985e0a881e9",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Contact Quality Has Been Falling Since Spring, and Whiffs Aren't the Reason\"\ndescription: \"Hard-hit rate and exit velocity have declined for months running, home run rate and wOBA cooled off after peaking in June, and whiff rate hasn't moved at all, a league-wide Statcast trend check through early August.\"\ndate: 2026-08-11\ncategories: [Baseball, Featured, Trend Watch]\n---\n\nOur [first-half review](/posts/baseball/2026-07-13-first-half-review/index.qmd)\npost noted league-wide wOBA climbing from .317 in March to .334 by June,\nand credited warmer air and hitters getting more reps as the season went\non. A month of additional data changes that story in a specific way:\nthe offensive climb already peaked in June, contact quality itself had\nalready started slipping before that, and the two trends didn't move\ntogether the way you'd expect.\n\n## The season, month by month\n\n::: {#cell-fetch-monthly-trend .cell execution_count=1}\n``` {.python .cell-code}\nfrom google.cloud import bigquery\n\nclient = bigquery.Client()\n\nmonthly_query = \"\"\"\nSELECT\n  FORMAT_DATE('%Y-%m', CAST(game_date AS DATE)) AS month,\n  COUNT(DISTINCT game_pk) AS games,\n  ROUND(SAFE_DIVIDE(SUM(woba_value), SUM(woba_denom)), 3) AS lg_woba,\n  ROUND(SAFE_DIVIDE(COUNTIF(events = 'strikeout'), COUNTIF(events IS NOT NULL)), 3) AS k_rate,\n  ROUND(SAFE_DIVIDE(COUNTIF(events = 'walk'), COUNTIF(events IS NOT NULL)), 3) AS bb_rate,\n  ROUND(SAFE_DIVIDE(COUNTIF(events = 'home_run'), COUNTIF(events IS NOT NULL)), 4) AS hr_rate,\n  ROUND(SAFE_DIVIDE(COUNTIF(description IN ('swinging_strike', 'swinging_strike_blocked')), COUNTIF(description IS NOT NULL)), 3) AS whiff_rate,\n  ROUND(AVG(launch_speed), 2) AS avg_exit_velo,\n  ROUND(SAFE_DIVIDE(COUNTIF(launch_speed >= 95), COUNTIF(launch_speed IS NOT NULL)), 3) AS hard_hit_rate,\n  ROUND(AVG(IF(pitch_type IN ('FF', 'SI'), release_speed, NULL)), 2) AS avg_fastball_velo\nFROM `maydaystats.mlb_statcast.pitches`\nWHERE game_type = 'R'\nGROUP BY month\nORDER BY month\n\"\"\"\n\nmonthly = client.query(monthly_query).to_dataframe()\nmonthly_tbl = monthly.reset_index(drop=True)\nmonthly_tbl.index += 1\nmonthly_tbl\n```\n\n::: {#fetch-monthly-trend .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>month</th>\n      <th>games</th>\n      <th>lg_woba</th>\n      <th>k_rate</th>\n      <th>bb_rate</th>\n      <th>hr_rate</th>\n      <th>whiff_rate</th>\n      <th>avg_exit_velo</th>\n      <th>hard_hit_rate</th>\n      <th>avg_fastball_velo</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>2026-03</td>\n      <td>76</td>\n      <td>0.317</td>\n      <td>0.244</td>\n      <td>0.095</td>\n      <td>0.0279</td>\n      <td>0.119</td>\n      <td>82.67</td>\n      <td>0.247</td>\n      <td>94.49</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2026-04</td>\n      <td>392</td>\n      <td>0.328</td>\n      <td>0.216</td>\n      <td>0.092</td>\n      <td>0.0281</td>\n      <td>0.106</td>\n      <td>82.67</td>\n      <td>0.249</td>\n      <td>94.29</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2026-05</td>\n      <td>419</td>\n      <td>0.320</td>\n      <td>0.218</td>\n      <td>0.085</td>\n      <td>0.0284</td>\n      <td>0.107</td>\n      <td>82.77</td>\n      <td>0.244</td>\n      <td>94.50</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2026-06</td>\n      <td>394</td>\n      <td>0.334</td>\n      <td>0.222</td>\n      <td>0.083</td>\n      <td>0.0342</td>\n      <td>0.109</td>\n      <td>82.51</td>\n      <td>0.240</td>\n      <td>94.69</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>2026-07</td>\n      <td>371</td>\n      <td>0.327</td>\n      <td>0.222</td>\n      <td>0.082</td>\n      <td>0.0319</td>\n      <td>0.110</td>\n      <td>82.47</td>\n      <td>0.235</td>\n      <td>94.64</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>2026-08</td>\n      <td>124</td>\n      <td>0.323</td>\n      <td>0.220</td>\n      <td>0.088</td>\n      <td>0.0295</td>\n      <td>0.107</td>\n      <td>82.35</td>\n      <td>0.229</td>\n      <td>94.66</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-fig-woba-by-month .cell execution_count=2}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nfig, ax = plt.subplots(figsize=(8, 5))\nax.plot(monthly[\"month\"], monthly[\"lg_woba\"], marker=\"o\", linewidth=2.5, color=\"#2c3e50\")\nax.set_ylabel(\"wOBA\")\nax.set_title(\"League wOBA by Month, 2026\")\nax.spines[[\"top\", \"right\"]].set_visible(False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![League-wide wOBA by month, the headline number behind the table above](index_files/figure-html/fig-woba-by-month-output-1.png){#fig-woba-by-month width=761 height=470}\n:::\n:::\n\n\nThe shape of the season is right there at a glance: a climb from March\ninto June, then two months easing back down. Everything below is about\nwhat's actually driving that second half of the curve.\n\nAugust is a partial month so far, but it's a real sample: 124 games as\nof this writing, more than a third of a full month's slate. Fastball\nvelocity has stayed essentially flat all season (94.3 to 94.7 mph, no\nreal trend either way), so nothing below is explained by pitchers\nsuddenly throwing softer.\n\n## Contact quality has been sliding since spring\n\n::: {#cell-fig-contact-vs-whiff .cell execution_count=3}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(8, 5))\nax.plot(monthly[\"month\"], monthly[\"hard_hit_rate\"], marker=\"o\", linewidth=2.5, color=\"#2c3e50\", label=\"Hard-hit rate\")\nax.plot(monthly[\"month\"], monthly[\"whiff_rate\"], marker=\"o\", linewidth=2.5, color=\"#c0392b\", label=\"Whiff rate\")\nax.set_ylabel(\"Rate\")\nax.set_title(\"Contact Quality Is Falling; Whiffs Aren't Rising\")\nax.spines[[\"top\", \"right\"]].set_visible(False)\nax.legend(loc=\"upper center\", bbox_to_anchor=(0.5, -0.12), ncol=2, frameon=False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Hard-hit rate vs. whiff rate, by month](index_files/figure-html/fig-contact-vs-whiff-output-1.png){#fig-contact-vs-whiff width=760 height=468}\n:::\n:::\n\n\nHard-hit rate (batted balls at 95 mph or above) peaked in April at .249\nand has fallen every single month since: .244 in May, .240 in June,\n.235 in July, .229 in August, its lowest point of the season and four\nstraight months of decline. Average exit velocity tells a similar\nstory on a smaller scale, peaking in May at 82.77 mph and drifting down\nto 82.35 by August.\n\nWhiff rate is the piece that rules out the obvious explanation. If\nhitters were simply missing the ball more often, that alone could\nexplain weaker results without any real change in the quality of\ntheir contact. That's not what's happening here: whiff rate has sat\nin a narrow .106 to .110 band every month since April, no trend in\neither direction. Hitters are making contact just as often as they\nwere in the spring. They're just not hitting it as hard when they do.\n\n## Home runs and wOBA didn't cool off until a month later\n\n::: {#cell-fig-hr-rate-by-month .cell execution_count=4}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(8, 5))\nax.bar(monthly[\"month\"], monthly[\"hr_rate\"], color=\"#2c3e50\")\nax.set_xlabel(\"Month\")\nax.set_ylabel(\"Home runs per plate appearance\")\nax.set_title(\"League HR Rate by Month, 2026\")\nax.spines[[\"top\", \"right\"]].set_visible(False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![League-wide home run rate per plate appearance, by month](index_files/figure-html/fig-hr-rate-by-month-output-1.png){#fig-hr-rate-by-month width=760 height=470}\n:::\n:::\n\n\nHere's the part that doesn't fit a simple story. Hard-hit rate was\nalready declining in May, but home run rate and wOBA kept climbing\nthrough June (.0342 HR rate, .334 wOBA, both season highs) before\nturning down in July and again in August (.0295 and .323). For about\ntwo months, production kept rising even as the underlying contact\nquality behind it was already softening. Warmer air carrying more\nfly balls out, the explanation our first-half post offered for the\nspring climb, could plausibly cover that gap for a while: a ball hit\na little softer can still leave the park in July heat if it wouldn't\nhave in April. By August, whatever cushion that provided evidently\nwasn't enough to offset four months of declining hard-hit rate, and\nproduction caught down to where contact quality already was.\n\nThat's a hypothesis this data can't fully confirm since we don't have\na clean way to isolate weather's effect pitch by pitch, but it fits the\ntimeline better than assuming contact quality and production should\nmove together in lockstep every month.\n\n## What this doesn't say\n\nThis is four and a half months of one season, not a multi-year signal,\nand August is still filling in: the 124 games behind this month's row\nin the table above will grow into a full slate over the next few weeks,\nand that number could move. I'll post a follow-up piece once August\ncompletes.\n\n::: {.callout-note}\nThis post uses Quarto's frozen execution (`freeze: auto`): the numbers\nabove reflect `mlb_statcast.pitches` as of whenever this was last\nrendered locally, not a live query on every page load. August figures\nin particular will look different on a re-render as the month fills\nin.\n:::\n\n",
    "supporting": [
      "index_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}