{
  "hash": "2b2d70eade5a82089b5f75ab74002c95",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"First Half in Review: Hitting and Pitching Trends, Team Momentum, and the Reds\"\ndescription: \"How league-wide hitting and pitching have shifted since March, which teams are actually trending up or down heading into the second half, and a data-driven look at where Cincinnati's offense and pitching staff really stand.\"\ndate: 2026-07-13\ncategories: [Baseball, Featured, Season Recap]\n---\n\nEvery team has now played most of its schedule, and with our\n[Statcast pipeline](/posts/baseball/2026-07-08-first-pitches/index.qmd)\nholding a full first half of pitch-level data (March 25 through July 12),\nand having just covered the\n[All-Star rosters themselves](/posts/baseball/2026-07-10-all-star-reality-check/index.qmd),\nit's a good moment to ask three broader questions: how has hitting and\npitching around the league actually changed since Opening Day, which\nteams are genuinely trending up or down heading into the second half, and\nhow do our own team's hitting and pitching numbers, the Cincinnati Reds,\nactually add up.\n\n## How the league has hit and pitched so far\n\n::: {#cell-fetch-monthly-trends .cell execution_count=1}\n``` {.python .cell-code}\nfrom google.cloud import bigquery\nimport pandas as pd\n\nclient = bigquery.Client()\n\nmonthly_query = \"\"\"\nSELECT\n  FORMAT_DATE('%Y-%m', CAST(game_date AS DATE)) AS month,\n  ROUND(SUM(woba_value)/SUM(woba_denom), 3) AS lg_woba,\n  ROUND(SAFE_DIVIDE(COUNTIF(events = 'strikeout'), COUNTIF(events IS NOT NULL)), 3) AS k_rate,\n  ROUND(SAFE_DIVIDE(COUNTIF(events = 'home_run'), COUNTIF(events IS NOT NULL)), 4) AS hr_rate,\n  ROUND(AVG(IF(pitch_type IN ('FF', 'SI'), release_speed, NULL)), 1) AS avg_fastball_velo,\n  ROUND(SAFE_DIVIDE(COUNTIF(description IN ('swinging_strike', 'swinging_strike_blocked')), COUNTIF(description IS NOT NULL)), 3) AS whiff_rate\nFROM `maydaystats.mlb_statcast.pitches`\nWHERE game_type = 'R'\nGROUP BY month\nORDER BY month\n\"\"\"\n\nmonthly = client.query(monthly_query).to_dataframe()\nmonthly_tbl = monthly.reset_index(drop=True)\nmonthly_tbl.index += 1\nmonthly_tbl\n```\n\n::: {#fetch-monthly-trends .cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>month</th>\n      <th>lg_woba</th>\n      <th>k_rate</th>\n      <th>hr_rate</th>\n      <th>avg_fastball_velo</th>\n      <th>whiff_rate</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>2026-03</td>\n      <td>0.317</td>\n      <td>0.244</td>\n      <td>0.0279</td>\n      <td>94.5</td>\n      <td>0.119</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2026-04</td>\n      <td>0.328</td>\n      <td>0.216</td>\n      <td>0.0281</td>\n      <td>94.3</td>\n      <td>0.106</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>2026-05</td>\n      <td>0.320</td>\n      <td>0.218</td>\n      <td>0.0284</td>\n      <td>94.5</td>\n      <td>0.107</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>2026-06</td>\n      <td>0.334</td>\n      <td>0.222</td>\n      <td>0.0342</td>\n      <td>94.7</td>\n      <td>0.109</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>2026-07</td>\n      <td>0.332</td>\n      <td>0.221</td>\n      <td>0.0353</td>\n      <td>94.7</td>\n      <td>0.108</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-fig-hr-rate-by-month .cell execution_count=2}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nfig, ax = plt.subplots(figsize=(8, 5))\nax.bar(monthly[\"month\"], monthly[\"hr_rate\"], color=\"#2c3e50\")\nax.set_xlabel(\"Month\")\nax.set_ylabel(\"Home runs per plate appearance\")\nax.set_title(\"League HR Rate by Month, 2026 First Half\")\nax.spines[[\"top\", \"right\"]].set_visible(False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![League-wide home run rate per plate appearance, by month](index_files/figure-html/fig-hr-rate-by-month-output-1.png){#fig-hr-rate-by-month width=760 height=470}\n:::\n:::\n\n\nA couple of these columns are worth defining before going further. wOBA\n(weighted on-base average) is the rate stat used throughout this post\ninstead of batting average or OPS, because it assigns each outcome, a\nwalk, a single, a double, a home run, and so on, its actual measured run\nvalue rather than treating every hit the same way or adding two\ndifferently-scaled numbers together. A .330 wOBA is roughly league\naverage; anything north of .370 is excellent. Whiff rate is simply the\nshare of pitches a hitter swings at and misses entirely, a proxy for how\noften pitchers are missing bats regardless of the final result.\n\nWith those defined, the league-wide numbers tell a fairly consistent\nstory as the season has warmed up: home run rate has climbed from 2.8%\nof plate appearances in March to 3.5% in July, a jump of roughly a\nquarter, and wOBA has followed the same direction, up from .317 to\n.332. Strikeout rate has eased at the same time, down from 24.4% to\n22.1%. The pitching side of the ledger hasn't moved much to explain\nthat: average fastball velocity has held steady around 94.5 mph all\nseason, and whiff rate has barely budged (11.9% in March, 10.8% in\nJuly). Pitchers aren't\nthrowing softer or missing fewer bats; hitters are simply doing more\ndamage on the contact they were already making. Two things typically get\ncredited for that, and this data can't cleanly separate them: the ball\ncarries better in warmer summer air, and hitters are also just more\nlocked in by June and July, with a few extra months of live at-bats to\ngroove their timing against pitching they've now often seen once\nalready. None of this is unique to this season, but it's a useful\nreminder that\nstats collected in April and stats collected in July aren't quite the\nsame measurement, which matters for the next question: which individual\nhitters and pitchers are actually trending, separate from that\nleague-wide drift.\n\n::: {#fetch-batter-movers .cell execution_count=3}\n``` {.python .cell-code}\nmovers_query = \"\"\"\nWITH pa AS (\n  SELECT\n    batter,\n    CAST(game_date AS DATE) AS game_date,\n    woba_value, woba_denom\n  FROM `maydaystats.mlb_statcast.pitches`\n  WHERE game_type = 'R' AND woba_denom IS NOT NULL\n),\nmax_date AS (SELECT MAX(game_date) AS d FROM pa),\nsplits AS (\n  SELECT\n    batter,\n    SUM(IF(game_date < DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), woba_value, 0)) AS early_val,\n    SUM(IF(game_date < DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), woba_denom, 0)) AS early_pa,\n    SUM(IF(game_date >= DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), woba_value, 0)) AS recent_val,\n    SUM(IF(game_date >= DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), woba_denom, 0)) AS recent_pa\n  FROM pa\n  GROUP BY batter\n)\nSELECT\n  b.player_name, b.team_name,\n  s.early_pa, ROUND(s.early_val / s.early_pa, 3) AS early_woba,\n  s.recent_pa, ROUND(s.recent_val / s.recent_pa, 3) AS recent_woba,\n  ROUND(s.recent_val / s.recent_pa - s.early_val / s.early_pa, 3) AS woba_delta\nFROM splits s\nJOIN `maydaystats.mlb_season_stats.batting_latest` b ON b.player_id = s.batter\nWHERE s.early_pa >= 100 AND s.recent_pa >= 100\nORDER BY woba_delta DESC\n\"\"\"\n\nmovers = client.query(movers_query).to_dataframe()\nrisers = movers.head(5).reset_index(drop=True)\nrisers.index += 1\nfallers = movers.tail(5).sort_values(\"woba_delta\").reset_index(drop=True)\nfallers.index += 1\n```\n:::\n\n\nSplitting each qualified hitter's plate appearances into \"before the last\n45 days\" and \"the last 45 days\" isolates real in-season swings from that\nseasonal drift. The clearest risers:\n\n::: {#tbl-batter-risers .cell tbl-cap='Biggest wOBA gainers, early season vs. last 45 days (min. 100 PA in each window)' execution_count=4}\n``` {.python .cell-code}\nrisers[[\"player_name\", \"team_name\", \"early_woba\", \"recent_woba\", \"woba_delta\"]]\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>player_name</th>\n      <th>team_name</th>\n      <th>early_woba</th>\n      <th>recent_woba</th>\n      <th>woba_delta</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>Pete Crow-Armstrong</td>\n      <td>Chicago Cubs</td>\n      <td>0.307</td>\n      <td>0.507</td>\n      <td>0.200</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Kyle Karros</td>\n      <td>Colorado Rockies</td>\n      <td>0.289</td>\n      <td>0.460</td>\n      <td>0.170</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Caleb Durbin</td>\n      <td>Boston Red Sox</td>\n      <td>0.236</td>\n      <td>0.385</td>\n      <td>0.149</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Victor Caratini</td>\n      <td>Minnesota Twins</td>\n      <td>0.256</td>\n      <td>0.404</td>\n      <td>0.148</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Tyler Soderstrom</td>\n      <td>Athletics</td>\n      <td>0.314</td>\n      <td>0.461</td>\n      <td>0.147</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nAnd the clearest decliners:\n\n::: {#tbl-batter-fallers .cell tbl-cap='Biggest wOBA decliners, early season vs. last 45 days (min. 100 PA in each window)' execution_count=5}\n``` {.python .cell-code}\nfallers[[\"player_name\", \"team_name\", \"early_woba\", \"recent_woba\", \"woba_delta\"]]\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>player_name</th>\n      <th>team_name</th>\n      <th>early_woba</th>\n      <th>recent_woba</th>\n      <th>woba_delta</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>Drake Baldwin</td>\n      <td>Atlanta Braves</td>\n      <td>0.409</td>\n      <td>0.225</td>\n      <td>-0.184</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Luke Raley</td>\n      <td>Seattle Mariners</td>\n      <td>0.377</td>\n      <td>0.254</td>\n      <td>-0.123</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Ildemaro Vargas</td>\n      <td>Arizona Diamondbacks</td>\n      <td>0.363</td>\n      <td>0.243</td>\n      <td>-0.120</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Oswald Peraza</td>\n      <td>Los Angeles Angels</td>\n      <td>0.363</td>\n      <td>0.244</td>\n      <td>-0.119</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Travis Bazzana</td>\n      <td>Cleveland Guardians</td>\n      <td>0.393</td>\n      <td>0.276</td>\n      <td>-0.117</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe Cubs' Pete Crow-Armstrong tops the risers, and two names on the\ndecliner list are worth pausing on: Atlanta's Drake Baldwin, the NL's\nelected starting catcher, is the single biggest decliner in baseball\nover this stretch, and Cleveland's Travis Bazzana, an AL player-elected\npick, isn't far off that pace either, both All-Stars in our\n[earlier piece on the fan vote](/posts/baseball/2026-07-10-all-star-reality-check/index.qmd).\nThat's not an argument against either selection; the vote reflects the\nseason as a whole, and both still have real first halves behind them.\nIt's just a sign of where each of them stands heading into the second\nhalf.\n\nThe same split works just as well from the pitcher's side of the ball,\nusing opponent wOBA (what a pitcher's batters have actually done against\nhim) instead of a pitcher's own wOBA. Starters and relievers are shown\nseparately below, since the two roles face lineups differently (starters\nwork through a batting order multiple times, relievers usually face it\nonce) and mixing them together makes both lists harder to read.\n\n::: {#fetch-pitcher-movers .cell execution_count=6}\n``` {.python .cell-code}\npitcher_movers_query = \"\"\"\nWITH pa AS (\n  SELECT\n    pitcher,\n    CAST(game_date AS DATE) AS game_date,\n    woba_value, woba_denom\n  FROM `maydaystats.mlb_statcast.pitches`\n  WHERE game_type = 'R' AND woba_denom IS NOT NULL\n),\nmax_date AS (SELECT MAX(game_date) AS d FROM pa),\nsplits AS (\n  SELECT\n    pitcher,\n    SUM(IF(game_date < DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), woba_value, 0)) AS early_val,\n    SUM(IF(game_date < DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), woba_denom, 0)) AS early_bf,\n    SUM(IF(game_date >= DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), woba_value, 0)) AS recent_val,\n    SUM(IF(game_date >= DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), woba_denom, 0)) AS recent_bf\n  FROM pa\n  GROUP BY pitcher\n)\nSELECT\n  p.player_name, p.team_name,\n  IF(SAFE_DIVIDE(p.gamesStarted, p.gamesPitched) >= 0.5, 'Starter', 'Reliever') AS role,\n  s.early_bf, ROUND(s.early_val / s.early_bf, 3) AS early_woba_against,\n  s.recent_bf, ROUND(s.recent_val / s.recent_bf, 3) AS recent_woba_against,\n  ROUND(s.recent_val / s.recent_bf - s.early_val / s.early_bf, 3) AS woba_against_delta\nFROM splits s\nJOIN `maydaystats.mlb_season_stats.pitching_latest` p ON p.player_id = s.pitcher\nWHERE s.early_bf >= 60 AND s.recent_bf >= 60\nORDER BY woba_against_delta ASC\n\"\"\"\n\npitcher_movers = client.query(pitcher_movers_query).to_dataframe()\ncols = [\"player_name\", \"team_name\", \"early_woba_against\", \"recent_woba_against\", \"woba_against_delta\"]\n\nstarters = pitcher_movers[pitcher_movers[\"role\"] == \"Starter\"].sort_values(\"woba_against_delta\")\nstarter_movers = pd.concat([starters.head(4), starters.tail(4)])[cols].reset_index(drop=True)\nstarter_movers.index += 1\n\nrelievers = pitcher_movers[pitcher_movers[\"role\"] == \"Reliever\"].sort_values(\"woba_against_delta\")\nreliever_movers = pd.concat([relievers.head(4), relievers.tail(4)])[cols].reset_index(drop=True)\nreliever_movers.index += 1\n```\n:::\n\n\nStarters, biggest opponent-wOBA improvers and decliners:\n\n::: {#tbl-starter-movers .cell tbl-cap='Starters: biggest opponent-wOBA swings, early season vs. last 45 days (min. 60 batters faced in each window)' execution_count=7}\n``` {.python .cell-code}\nstarter_movers\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>player_name</th>\n      <th>team_name</th>\n      <th>early_woba_against</th>\n      <th>recent_woba_against</th>\n      <th>woba_against_delta</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>Jack Flaherty</td>\n      <td>Detroit Tigers</td>\n      <td>0.384</td>\n      <td>0.267</td>\n      <td>-0.117</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Brayan Bello</td>\n      <td>Boston Red Sox</td>\n      <td>0.396</td>\n      <td>0.280</td>\n      <td>-0.116</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Trevor Rogers</td>\n      <td>Baltimore Orioles</td>\n      <td>0.382</td>\n      <td>0.269</td>\n      <td>-0.113</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Eury Pérez</td>\n      <td>Miami Marlins</td>\n      <td>0.338</td>\n      <td>0.228</td>\n      <td>-0.110</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Stephen Kolek</td>\n      <td>Kansas City Royals</td>\n      <td>0.249</td>\n      <td>0.400</td>\n      <td>0.151</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Mitch Keller</td>\n      <td>Pittsburgh Pirates</td>\n      <td>0.270</td>\n      <td>0.426</td>\n      <td>0.155</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Andrew Painter</td>\n      <td>Philadelphia Phillies</td>\n      <td>0.350</td>\n      <td>0.507</td>\n      <td>0.157</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Randy Vásquez</td>\n      <td>San Diego Padres</td>\n      <td>0.324</td>\n      <td>0.489</td>\n      <td>0.164</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nRelievers, the same split:\n\n::: {#tbl-reliever-movers .cell tbl-cap='Relievers: biggest opponent-wOBA swings, early season vs. last 45 days (min. 60 batters faced in each window)' execution_count=8}\n``` {.python .cell-code}\nreliever_movers\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>player_name</th>\n      <th>team_name</th>\n      <th>early_woba_against</th>\n      <th>recent_woba_against</th>\n      <th>woba_against_delta</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>Trevor Megill</td>\n      <td>Milwaukee Brewers</td>\n      <td>0.289</td>\n      <td>0.179</td>\n      <td>-0.110</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Greg Weissert</td>\n      <td>Boston Red Sox</td>\n      <td>0.346</td>\n      <td>0.239</td>\n      <td>-0.107</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Paul Blackburn</td>\n      <td>New York Yankees</td>\n      <td>0.316</td>\n      <td>0.216</td>\n      <td>-0.099</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Yohan Ramírez</td>\n      <td>Pittsburgh Pirates</td>\n      <td>0.366</td>\n      <td>0.268</td>\n      <td>-0.098</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Gregory Soto</td>\n      <td>Pittsburgh Pirates</td>\n      <td>0.211</td>\n      <td>0.399</td>\n      <td>0.188</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Tobias Myers</td>\n      <td>New York Mets</td>\n      <td>0.294</td>\n      <td>0.498</td>\n      <td>0.203</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Joel Kuhnel</td>\n      <td>Milwaukee Brewers</td>\n      <td>0.276</td>\n      <td>0.486</td>\n      <td>0.210</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Antonio Senzatela</td>\n      <td>Colorado Rockies</td>\n      <td>0.217</td>\n      <td>0.434</td>\n      <td>0.217</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nTwo names on the starter improvers list are worth flagging now, because\nthey show up again in the next section: Detroit's Jack Flaherty and\nMiami's Eury Pérez have both cut real ground off their opponent wOBA,\nand both of their teams are about to turn up as the two clearest hot\nstreaks in baseball.\n\n## Which teams are trending, and is any of it real\n\nRecords can move for two different reasons: a team is genuinely playing\nbetter or worse baseball, or the same underlying performance is just\nrunning into better or worse luck. Splitting each team's early season\nfrom its last 45 days, the same way as the hitters above, and pairing\nthe win rate with the underlying offensive and pitching quality (wOBA\nfor and against), separates the two.\n\n::: {#fetch-team-trend .cell execution_count=9}\n``` {.python .cell-code}\nteam_trend_query = \"\"\"\nWITH games AS (\n  SELECT\n    game_pk,\n    CAST(ANY_VALUE(game_date) AS DATE) AS game_date,\n    ANY_VALUE(home_team) AS home_team,\n    ANY_VALUE(away_team) AS away_team,\n    MAX(post_home_score) AS home_final,\n    MAX(post_away_score) AS away_final\n  FROM `maydaystats.mlb_statcast.pitches`\n  WHERE game_type = 'R'\n  GROUP BY game_pk\n),\nteam_games AS (\n  SELECT game_pk, game_date, home_team AS team,\n    IF(home_final > away_final, 1, 0) AS win\n  FROM games\n  UNION ALL\n  SELECT game_pk, game_date, away_team AS team,\n    IF(away_final > home_final, 1, 0) AS win\n  FROM games\n),\nmax_date AS (SELECT MAX(game_date) AS d FROM team_games),\nrecords AS (\n  SELECT\n    team,\n    ROUND(SAFE_DIVIDE(SUM(IF(game_date < DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), win, 0)),\n      SUM(IF(game_date < DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), 1, 0))), 3) AS early_wpct,\n    ROUND(SAFE_DIVIDE(SUM(IF(game_date >= DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), win, 0)),\n      SUM(IF(game_date >= DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), 1, 0))), 3) AS recent_wpct\n  FROM team_games\n  GROUP BY team\n),\npa AS (\n  SELECT\n    CAST(game_date AS DATE) AS game_date,\n    IF(inning_topbot = 'Top', away_team, home_team) AS bat_team,\n    IF(inning_topbot = 'Top', home_team, away_team) AS pit_team,\n    woba_value, woba_denom\n  FROM `maydaystats.mlb_statcast.pitches`\n  WHERE game_type = 'R' AND woba_denom IS NOT NULL\n),\nmax_pa_date AS (SELECT MAX(game_date) AS d FROM pa),\noff AS (\n  SELECT bat_team AS team,\n    ROUND(SAFE_DIVIDE(SUM(IF(game_date < DATE_SUB((SELECT d FROM max_pa_date), INTERVAL 45 DAY), woba_value, 0)),\n      SUM(IF(game_date < DATE_SUB((SELECT d FROM max_pa_date), INTERVAL 45 DAY), woba_denom, 0))), 3) AS off_early,\n    ROUND(SAFE_DIVIDE(SUM(IF(game_date >= DATE_SUB((SELECT d FROM max_pa_date), INTERVAL 45 DAY), woba_value, 0)),\n      SUM(IF(game_date >= DATE_SUB((SELECT d FROM max_pa_date), INTERVAL 45 DAY), woba_denom, 0))), 3) AS off_recent\n  FROM pa GROUP BY bat_team\n),\ndef AS (\n  SELECT pit_team AS team,\n    ROUND(SAFE_DIVIDE(SUM(IF(game_date < DATE_SUB((SELECT d FROM max_pa_date), INTERVAL 45 DAY), woba_value, 0)),\n      SUM(IF(game_date < DATE_SUB((SELECT d FROM max_pa_date), INTERVAL 45 DAY), woba_denom, 0))), 3) AS def_early,\n    ROUND(SAFE_DIVIDE(SUM(IF(game_date >= DATE_SUB((SELECT d FROM max_pa_date), INTERVAL 45 DAY), woba_value, 0)),\n      SUM(IF(game_date >= DATE_SUB((SELECT d FROM max_pa_date), INTERVAL 45 DAY), woba_denom, 0))), 3) AS def_recent\n  FROM pa GROUP BY pit_team\n)\nSELECT\n  r.team, r.early_wpct, r.recent_wpct,\n  ROUND(r.recent_wpct - r.early_wpct, 3) AS wpct_delta,\n  o.off_early, o.off_recent, ROUND(o.off_recent - o.off_early, 3) AS off_delta,\n  d.def_early, d.def_recent, ROUND(d.def_recent - d.def_early, 3) AS def_delta\nFROM records r\nJOIN off o ON o.team = r.team\nJOIN def d ON d.team = r.team\nORDER BY wpct_delta DESC\n\"\"\"\n\nteam_trend = client.query(team_trend_query).to_dataframe()\n\nTEAM_NAMES = {\n    \"ATH\": \"Athletics\", \"ATL\": \"Atlanta Braves\", \"AZ\": \"Arizona Diamondbacks\",\n    \"BAL\": \"Baltimore Orioles\", \"BOS\": \"Boston Red Sox\", \"CHC\": \"Chicago Cubs\",\n    \"CIN\": \"Cincinnati Reds\", \"CLE\": \"Cleveland Guardians\", \"COL\": \"Colorado Rockies\",\n    \"CWS\": \"Chicago White Sox\", \"DET\": \"Detroit Tigers\", \"HOU\": \"Houston Astros\",\n    \"KC\": \"Kansas City Royals\", \"LAA\": \"Los Angeles Angels\", \"LAD\": \"Los Angeles Dodgers\",\n    \"MIA\": \"Miami Marlins\", \"MIL\": \"Milwaukee Brewers\", \"MIN\": \"Minnesota Twins\",\n    \"NYM\": \"New York Mets\", \"NYY\": \"New York Yankees\", \"PHI\": \"Philadelphia Phillies\",\n    \"PIT\": \"Pittsburgh Pirates\", \"SD\": \"San Diego Padres\", \"SEA\": \"Seattle Mariners\",\n    \"SF\": \"San Francisco Giants\", \"STL\": \"St. Louis Cardinals\", \"TB\": \"Tampa Bay Rays\",\n    \"TEX\": \"Texas Rangers\", \"TOR\": \"Toronto Blue Jays\", \"WSH\": \"Washington Nationals\",\n}\nteam_trend[\"team_name\"] = team_trend[\"team\"].map(TEAM_NAMES)\n\nmovers_teams = pd.concat([team_trend.head(5), team_trend.tail(5)])\n```\n:::\n\n\n::: {#cell-fig-team-wpct-swing .cell execution_count=10}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(8, 6))\nplot_teams = movers_teams.iloc[::-1]\ncolors = [\"#2c3e50\" if v > 0 else \"#c0392b\" for v in plot_teams[\"wpct_delta\"]]\nax.barh(plot_teams[\"team_name\"], plot_teams[\"wpct_delta\"], color=colors)\nax.set_xlabel(\"Win rate change (recent 45 days minus early season)\")\nax.set_title(\"Biggest Team Win-Rate Swings\")\nax.spines[[\"top\", \"right\"]].set_visible(False)\nax.axvline(0, color=\"#888888\", linewidth=0.8)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Biggest win-rate swings, early season vs. last 45 days](index_files/figure-html/fig-team-wpct-swing-output-1.png){#fig-team-wpct-swing width=765 height=566}\n:::\n:::\n\n\n::: {#tbl-team-trend .cell tbl-cap='Win rate, offensive wOBA, and opponent wOBA allowed (pitching) trend for the biggest movers' execution_count=11}\n``` {.python .cell-code}\ntrend_tbl = movers_teams[[\"team_name\", \"wpct_delta\", \"off_delta\", \"def_delta\"]].rename(\n    columns={\"off_delta\": \"batting_woba_delta\", \"def_delta\": \"pitching_woba_allowed_delta\"}\n).reset_index(drop=True)\ntrend_tbl.index += 1\ntrend_tbl\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>team_name</th>\n      <th>wpct_delta</th>\n      <th>batting_woba_delta</th>\n      <th>pitching_woba_allowed_delta</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>Miami Marlins</td>\n      <td>0.194</td>\n      <td>0.037</td>\n      <td>-0.007</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Detroit Tigers</td>\n      <td>0.157</td>\n      <td>0.019</td>\n      <td>-0.019</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Boston Red Sox</td>\n      <td>0.149</td>\n      <td>0.007</td>\n      <td>-0.018</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Texas Rangers</td>\n      <td>0.130</td>\n      <td>0.026</td>\n      <td>0.025</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Colorado Rockies</td>\n      <td>0.112</td>\n      <td>0.054</td>\n      <td>0.021</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Arizona Diamondbacks</td>\n      <td>-0.125</td>\n      <td>-0.019</td>\n      <td>0.027</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Athletics</td>\n      <td>-0.132</td>\n      <td>0.002</td>\n      <td>0.035</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>San Diego Padres</td>\n      <td>-0.149</td>\n      <td>0.021</td>\n      <td>0.047</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Cincinnati Reds</td>\n      <td>-0.177</td>\n      <td>-0.011</td>\n      <td>-0.001</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>Atlanta Braves</td>\n      <td>-0.199</td>\n      <td>-0.026</td>\n      <td>0.035</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nMiami and Detroit are the two clearest hot streaks backed by real\nsubstance, not just a stretch of good luck. Miami's win rate has jumped\nfrom .456 to .650 over the last 45 days, driven mostly by a real gain in\nteam batting wOBA, with Eury Pérez's improvement from the last section\ndoing its part on the mound too. Detroit's climb from .393 to .550 is\njust as real, and backed on both sides of the ball: batting wOBA up, and\nless wOBA allowed by the pitching staff, with Jack Flaherty leading that\ncharge. Atlanta sits at the other end: a win rate that fell from .661\ndown to .462, matched by real decline in both their hitting and their\npitching.\n\nCincinnati and San Diego both show declines where the win rate moved\nfurther than the underlying numbers would suggest, which is a sign that\nsome of the drop is bad sequencing rather than the whole roster\nsuddenly playing worse. For the Reds, that's worth a full section of its\nown; for San Diego, the driver looks specifically like the pitching\nstaff, whose opponent wOBA allowed climbed sharply even as the offense\nactually improved.\n\n## A closer look at the Reds\n\n::: {#cell-fetch-reds-standings .cell execution_count=12}\n``` {.python .cell-code}\nstandings_query = \"\"\"\nWITH games AS (\n  SELECT\n    game_pk,\n    ANY_VALUE(home_team) AS home_team,\n    ANY_VALUE(away_team) AS away_team,\n    MAX(post_home_score) AS home_final,\n    MAX(post_away_score) AS away_final\n  FROM `maydaystats.mlb_statcast.pitches`\n  WHERE game_type = 'R'\n  GROUP BY game_pk\n),\nteam_games AS (\n  SELECT home_team AS team, IF(home_final > away_final, 1, 0) AS win FROM games\n  UNION ALL\n  SELECT away_team AS team, IF(away_final > home_final, 1, 0) AS win FROM games\n)\nSELECT team, COUNT(*) AS games, SUM(win) AS wins, COUNT(*) - SUM(win) AS losses,\n  ROUND(SAFE_DIVIDE(SUM(win), COUNT(*)), 3) AS win_pct\nFROM team_games\nWHERE team IN ('MIL', 'CHC', 'STL', 'PIT', 'CIN')\nGROUP BY team\nORDER BY win_pct DESC\n\"\"\"\n\nstandings = client.query(standings_query).to_dataframe()\nstandings[\"team\"] = standings[\"team\"].map(TEAM_NAMES)\nstandings_tbl = standings.reset_index(drop=True)\nstandings_tbl.index += 1\nstandings_tbl\n```\n\n::: {#fetch-reds-standings .cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>team</th>\n      <th>games</th>\n      <th>wins</th>\n      <th>losses</th>\n      <th>win_pct</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>Milwaukee Brewers</td>\n      <td>96</td>\n      <td>59</td>\n      <td>37</td>\n      <td>0.615</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Chicago Cubs</td>\n      <td>96</td>\n      <td>54</td>\n      <td>42</td>\n      <td>0.563</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>St. Louis Cardinals</td>\n      <td>95</td>\n      <td>50</td>\n      <td>45</td>\n      <td>0.526</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Pittsburgh Pirates</td>\n      <td>97</td>\n      <td>50</td>\n      <td>47</td>\n      <td>0.515</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Cincinnati Reds</td>\n      <td>95</td>\n      <td>43</td>\n      <td>52</td>\n      <td>0.453</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe Reds go into the break in last place in the NL Central, nine games\nunder .500. Before getting into why, it's worth checking the most basic\nquestion directly: how many runs has this team actually been scoring\nand allowing.\n\n::: {#cell-fetch-reds-runs .cell execution_count=13}\n``` {.python .cell-code}\nruns_query = \"\"\"\nWITH games AS (\n  SELECT\n    game_pk,\n    CAST(ANY_VALUE(game_date) AS DATE) AS game_date,\n    ANY_VALUE(home_team) AS home_team,\n    ANY_VALUE(away_team) AS away_team,\n    MAX(post_home_score) AS home_final,\n    MAX(post_away_score) AS away_final\n  FROM `maydaystats.mlb_statcast.pitches`\n  WHERE game_type = 'R'\n  GROUP BY game_pk\n),\nteam_games AS (\n  SELECT game_pk, game_date, home_team AS team, home_final AS runs_scored, away_final AS runs_allowed FROM games\n  UNION ALL\n  SELECT game_pk, game_date, away_team AS team, away_final AS runs_scored, home_final AS runs_allowed FROM games\n),\nmax_date AS (SELECT MAX(game_date) AS d FROM team_games)\nSELECT\n  team,\n  ROUND(SUM(runs_scored) / COUNT(*), 2) AS rpg_season,\n  ROUND(SUM(runs_allowed) / COUNT(*), 2) AS runs_allowed_pg_season,\n  ROUND(SAFE_DIVIDE(SUM(IF(game_date >= DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), runs_scored, 0)),\n    SUM(IF(game_date >= DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), 1, 0))), 2) AS rpg_recent,\n  ROUND(SAFE_DIVIDE(SUM(IF(game_date >= DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), runs_allowed, 0)),\n    SUM(IF(game_date >= DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), 1, 0))), 2) AS runs_allowed_pg_recent\nFROM team_games\nGROUP BY team\n\"\"\"\nruns_all = client.query(runs_query).to_dataframe()\nlg_avg = runs_all[\"rpg_season\"].mean()\nreds_runs = runs_all[runs_all[\"team\"] == \"CIN\"].copy()\nreds_runs[\"team\"] = \"Cincinnati Reds\"\nreds_runs_tbl = reds_runs.reset_index(drop=True)\nreds_runs_tbl.index += 1\nreds_runs_tbl\n```\n\n::: {#fetch-reds-runs .cell-output .cell-output-display execution_count=13}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>team</th>\n      <th>rpg_season</th>\n      <th>runs_allowed_pg_season</th>\n      <th>rpg_recent</th>\n      <th>runs_allowed_pg_recent</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>Cincinnati Reds</td>\n      <td>4.16</td>\n      <td>4.79</td>\n      <td>3.75</td>\n      <td>4.6</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe Reds are averaging 4\\.16\nruns a game for the season, against a league average of\n4\\.52, which puts them in the bottom third of\nbaseball for scoring. That's not a recent development; it's been true\nmost of the year. What has changed is the size of the gap: scoring\ndropped further over the last 45 days, down to\n3\\.75 runs a game, while\nruns allowed actually improved slightly, from\n4\\.79 a game\nfor the season to 4\\.60\nrecently. In plain terms: this has been a below-average offense all\nyear, not a good offense that collapsed, and pitching has quietly held\nup better than the win-loss record suggests.\n\n::: {#cell-fetch-reds-hitters .cell execution_count=14}\n``` {.python .cell-code}\nreds_hitters_query = \"\"\"\nSELECT player_name, position, gamesPlayed, homeRuns, rbi,\n  CAST(avg AS FLOAT64) AS avg, CAST(obp AS FLOAT64) AS obp,\n  CAST(slg AS FLOAT64) AS slg, CAST(ops AS FLOAT64) AS ops, plateAppearances\nFROM `maydaystats.mlb_season_stats.batting_latest`\nWHERE team_name = 'Cincinnati Reds' AND plateAppearances >= 50\nORDER BY ops DESC\n\"\"\"\nreds_hitters = client.query(reds_hitters_query).to_dataframe()\nreds_hitters_tbl = reds_hitters.reset_index(drop=True)\nreds_hitters_tbl.index += 1\nreds_hitters_tbl\n```\n\n::: {#fetch-reds-hitters .cell-output .cell-output-display execution_count=14}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>player_name</th>\n      <th>position</th>\n      <th>gamesPlayed</th>\n      <th>homeRuns</th>\n      <th>rbi</th>\n      <th>avg</th>\n      <th>obp</th>\n      <th>slg</th>\n      <th>ops</th>\n      <th>plateAppearances</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>JJ Bleday</td>\n      <td>LF</td>\n      <td>67</td>\n      <td>16</td>\n      <td>43</td>\n      <td>0.242</td>\n      <td>0.350</td>\n      <td>0.496</td>\n      <td>0.846</td>\n      <td>284</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Elly De La Cruz</td>\n      <td>SS</td>\n      <td>76</td>\n      <td>15</td>\n      <td>44</td>\n      <td>0.274</td>\n      <td>0.347</td>\n      <td>0.492</td>\n      <td>0.839</td>\n      <td>340</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Sal Stewart</td>\n      <td>1B</td>\n      <td>95</td>\n      <td>19</td>\n      <td>65</td>\n      <td>0.256</td>\n      <td>0.338</td>\n      <td>0.474</td>\n      <td>0.812</td>\n      <td>414</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Nathaniel Lowe</td>\n      <td>DH</td>\n      <td>70</td>\n      <td>10</td>\n      <td>26</td>\n      <td>0.247</td>\n      <td>0.335</td>\n      <td>0.465</td>\n      <td>0.800</td>\n      <td>224</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Spencer Steer</td>\n      <td>1B</td>\n      <td>91</td>\n      <td>14</td>\n      <td>37</td>\n      <td>0.247</td>\n      <td>0.328</td>\n      <td>0.421</td>\n      <td>0.749</td>\n      <td>358</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Dane Myers</td>\n      <td>CF</td>\n      <td>63</td>\n      <td>3</td>\n      <td>14</td>\n      <td>0.256</td>\n      <td>0.358</td>\n      <td>0.385</td>\n      <td>0.743</td>\n      <td>137</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Blake Dunn</td>\n      <td>CF</td>\n      <td>38</td>\n      <td>2</td>\n      <td>7</td>\n      <td>0.282</td>\n      <td>0.335</td>\n      <td>0.387</td>\n      <td>0.722</td>\n      <td>155</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Tyler Stephenson</td>\n      <td>C</td>\n      <td>73</td>\n      <td>6</td>\n      <td>24</td>\n      <td>0.238</td>\n      <td>0.319</td>\n      <td>0.361</td>\n      <td>0.680</td>\n      <td>257</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Eugenio Suárez</td>\n      <td>DH</td>\n      <td>67</td>\n      <td>11</td>\n      <td>35</td>\n      <td>0.208</td>\n      <td>0.285</td>\n      <td>0.388</td>\n      <td>0.673</td>\n      <td>267</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>Will Benson</td>\n      <td>RF</td>\n      <td>51</td>\n      <td>3</td>\n      <td>6</td>\n      <td>0.188</td>\n      <td>0.310</td>\n      <td>0.333</td>\n      <td>0.643</td>\n      <td>114</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>Noelvi Marte</td>\n      <td>RF</td>\n      <td>41</td>\n      <td>6</td>\n      <td>13</td>\n      <td>0.195</td>\n      <td>0.248</td>\n      <td>0.375</td>\n      <td>0.623</td>\n      <td>137</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>Matt McLain</td>\n      <td>2B</td>\n      <td>83</td>\n      <td>8</td>\n      <td>25</td>\n      <td>0.190</td>\n      <td>0.293</td>\n      <td>0.328</td>\n      <td>0.621</td>\n      <td>309</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>Jose Trevino</td>\n      <td>C</td>\n      <td>25</td>\n      <td>1</td>\n      <td>8</td>\n      <td>0.239</td>\n      <td>0.250</td>\n      <td>0.328</td>\n      <td>0.578</td>\n      <td>70</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>Edwin Arroyo</td>\n      <td>2B</td>\n      <td>33</td>\n      <td>0</td>\n      <td>4</td>\n      <td>0.240</td>\n      <td>0.280</td>\n      <td>0.290</td>\n      <td>0.570</td>\n      <td>108</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>TJ Friedl</td>\n      <td>CF</td>\n      <td>59</td>\n      <td>3</td>\n      <td>11</td>\n      <td>0.181</td>\n      <td>0.258</td>\n      <td>0.271</td>\n      <td>0.529</td>\n      <td>214</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>Ke'Bryan Hayes</td>\n      <td>3B</td>\n      <td>46</td>\n      <td>2</td>\n      <td>5</td>\n      <td>0.143</td>\n      <td>0.200</td>\n      <td>0.222</td>\n      <td>0.422</td>\n      <td>135</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nJJ Bleday narrowly leads the everyday lineup in OPS (.846), just ahead\nof Elly De La Cruz (.839). The underlying contact data points to De La\nCruz as the more dangerous hitter of the two, though: he produces the\nhardest, fastest contact on the entire roster, well clear of second\nplace.\n\n::: {#cell-fetch-reds-statcast .cell execution_count=15}\n``` {.python .cell-code}\nreds_contact_query = \"\"\"\nSELECT b.player_name,\n  ROUND(AVG(p.launch_speed), 1) AS avg_exit_velo,\n  ROUND(SAFE_DIVIDE(COUNTIF(p.launch_speed >= 95), COUNTIF(p.launch_speed IS NOT NULL)), 3) AS hard_hit_rate,\n  ROUND(AVG(p.bat_speed), 1) AS avg_bat_speed,\n  COUNT(p.launch_speed) AS batted_balls\nFROM `maydaystats.mlb_season_stats.batting_latest` b\nJOIN `maydaystats.mlb_statcast.pitches` p ON p.batter = b.player_id\nWHERE b.team_name = 'Cincinnati Reds' AND p.launch_speed IS NOT NULL AND p.game_type = 'R'\nGROUP BY b.player_name\nHAVING batted_balls >= 100\nORDER BY avg_exit_velo DESC\n\"\"\"\nreds_contact = client.query(reds_contact_query).to_dataframe()\nreds_contact_tbl = reds_contact.reset_index(drop=True)\nreds_contact_tbl.index += 1\nreds_contact_tbl\n```\n\n::: {#fetch-reds-statcast .cell-output .cell-output-display execution_count=15}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>player_name</th>\n      <th>avg_exit_velo</th>\n      <th>hard_hit_rate</th>\n      <th>avg_bat_speed</th>\n      <th>batted_balls</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>Elly De La Cruz</td>\n      <td>86.3</td>\n      <td>0.336</td>\n      <td>73.9</td>\n      <td>345</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Ke'Bryan Hayes</td>\n      <td>85.4</td>\n      <td>0.300</td>\n      <td>69.9</td>\n      <td>140</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Sal Stewart</td>\n      <td>84.8</td>\n      <td>0.257</td>\n      <td>71.7</td>\n      <td>486</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Tyler Stephenson</td>\n      <td>84.7</td>\n      <td>0.265</td>\n      <td>70.4</td>\n      <td>298</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Spencer Steer</td>\n      <td>84.5</td>\n      <td>0.263</td>\n      <td>70.3</td>\n      <td>407</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Eugenio Suárez</td>\n      <td>83.0</td>\n      <td>0.201</td>\n      <td>70.2</td>\n      <td>288</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>JJ Bleday</td>\n      <td>82.7</td>\n      <td>0.281</td>\n      <td>73.1</td>\n      <td>352</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Dane Myers</td>\n      <td>82.6</td>\n      <td>0.196</td>\n      <td>70.0</td>\n      <td>153</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Will Benson</td>\n      <td>82.6</td>\n      <td>0.220</td>\n      <td>72.5</td>\n      <td>109</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>Noelvi Marte</td>\n      <td>82.4</td>\n      <td>0.185</td>\n      <td>71.6</td>\n      <td>162</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>Edwin Arroyo</td>\n      <td>81.9</td>\n      <td>0.188</td>\n      <td>68.7</td>\n      <td>144</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>Matt McLain</td>\n      <td>81.9</td>\n      <td>0.218</td>\n      <td>70.7</td>\n      <td>344</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>Nathaniel Lowe</td>\n      <td>81.4</td>\n      <td>0.206</td>\n      <td>73.3</td>\n      <td>301</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>TJ Friedl</td>\n      <td>80.1</td>\n      <td>0.197</td>\n      <td>67.2</td>\n      <td>229</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>Blake Dunn</td>\n      <td>79.9</td>\n      <td>0.201</td>\n      <td>69.2</td>\n      <td>169</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThat contact-quality table also surfaces the more useful story on this\nroster: a gap between how well some of these hitters are actually\nsquaring up the ball and what their batting average says.\n\n::: {#cell-fetch-reds-luck .cell execution_count=16}\n``` {.python .cell-code}\nreds_luck_query = \"\"\"\nSELECT b.player_name,\n  ROUND(AVG(p.estimated_ba_using_speedangle), 3) AS xba,\n  CAST(b.avg AS FLOAT64) AS actual_avg,\n  ROUND(CAST(b.avg AS FLOAT64) - AVG(p.estimated_ba_using_speedangle), 3) AS avg_minus_xba,\n  COUNT(*) AS batted_balls\nFROM `maydaystats.mlb_season_stats.batting_latest` b\nJOIN `maydaystats.mlb_statcast.pitches` p ON p.batter = b.player_id\nWHERE b.team_name = 'Cincinnati Reds'\n  AND p.estimated_ba_using_speedangle IS NOT NULL AND p.game_type = 'R'\nGROUP BY b.player_name, b.avg\nHAVING batted_balls >= 90\nORDER BY avg_minus_xba ASC\n\"\"\"\nreds_luck = client.query(reds_luck_query).to_dataframe()\nreds_luck_tbl = reds_luck.head(5)[[\"player_name\", \"xba\", \"actual_avg\", \"avg_minus_xba\"]].reset_index(drop=True)\nreds_luck_tbl.index += 1\nreds_luck_tbl\n```\n\n::: {#fetch-reds-luck .cell-output .cell-output-display execution_count=16}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>player_name</th>\n      <th>xba</th>\n      <th>actual_avg</th>\n      <th>avg_minus_xba</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>Ke'Bryan Hayes</td>\n      <td>0.313</td>\n      <td>0.143</td>\n      <td>-0.170</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Matt McLain</td>\n      <td>0.329</td>\n      <td>0.190</td>\n      <td>-0.139</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Nathaniel Lowe</td>\n      <td>0.382</td>\n      <td>0.247</td>\n      <td>-0.135</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Elly De La Cruz</td>\n      <td>0.397</td>\n      <td>0.274</td>\n      <td>-0.123</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Eugenio Suárez</td>\n      <td>0.321</td>\n      <td>0.208</td>\n      <td>-0.113</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nKe'Bryan Hayes is the extreme case: Statcast's contact-quality model\nexpects a .313 batting average from the way he's hitting the ball, and\nhe's actually running a .143, the largest gap on the roster among\nplayers with a meaningful sample of batted balls. His exit velocity and\nhard-hit rate are both solidly average-or-better for this team; the\nresults just haven't shown up yet. Elly De La Cruz carries a smaller\nversion of the same gap (an expected .397 against an actual .274), which\nmatters more here because his actual season is already excellent; if\nthat gap closes at all, his results have real room to get even better.\nNone of this guarantees a second-half turnaround, but it lines up with\nthe team-wide finding from the last section: results that have fallen\nfurther than the process backing them up.\n\n::: {#cell-fetch-reds-pitching .cell execution_count=17}\n``` {.python .cell-code}\nreds_pitching_query = \"\"\"\nSELECT player_name,\n  IF(SAFE_DIVIDE(gamesStarted, gamesPitched) >= 0.5, 'Starter', 'Reliever') AS role,\n  wins, losses, CAST(era AS FLOAT64) AS era, strikeOuts,\n  CAST(whip AS FLOAT64) AS whip, CAST(inningsPitched AS FLOAT64) AS ip\nFROM `maydaystats.mlb_season_stats.pitching_latest`\nWHERE team_name = 'Cincinnati Reds' AND CAST(inningsPitched AS FLOAT64) >= 20\nORDER BY role, era ASC\n\"\"\"\nreds_pitching = client.query(reds_pitching_query).to_dataframe()\nreds_pitching_tbl = reds_pitching.reset_index(drop=True)\nreds_pitching_tbl.index += 1\nreds_pitching_tbl\n```\n\n::: {#fetch-reds-pitching .cell-output .cell-output-display execution_count=17}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>player_name</th>\n      <th>role</th>\n      <th>wins</th>\n      <th>losses</th>\n      <th>era</th>\n      <th>strikeOuts</th>\n      <th>whip</th>\n      <th>ip</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>Tejay Antone</td>\n      <td>Reliever</td>\n      <td>1</td>\n      <td>0</td>\n      <td>2.25</td>\n      <td>25</td>\n      <td>0.89</td>\n      <td>28.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Brock Burke</td>\n      <td>Reliever</td>\n      <td>3</td>\n      <td>4</td>\n      <td>3.02</td>\n      <td>39</td>\n      <td>1.39</td>\n      <td>44.2</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Graham Ashcraft</td>\n      <td>Reliever</td>\n      <td>1</td>\n      <td>1</td>\n      <td>3.33</td>\n      <td>32</td>\n      <td>1.22</td>\n      <td>27.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Sam Moll</td>\n      <td>Reliever</td>\n      <td>1</td>\n      <td>6</td>\n      <td>4.19</td>\n      <td>43</td>\n      <td>1.32</td>\n      <td>38.2</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Pierce Johnson</td>\n      <td>Reliever</td>\n      <td>2</td>\n      <td>1</td>\n      <td>4.23</td>\n      <td>25</td>\n      <td>1.30</td>\n      <td>27.2</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Chase Petty</td>\n      <td>Reliever</td>\n      <td>1</td>\n      <td>2</td>\n      <td>4.38</td>\n      <td>11</td>\n      <td>1.09</td>\n      <td>24.2</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Tony Santillan</td>\n      <td>Reliever</td>\n      <td>1</td>\n      <td>4</td>\n      <td>5.23</td>\n      <td>28</td>\n      <td>1.39</td>\n      <td>31.0</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Connor Phillips</td>\n      <td>Reliever</td>\n      <td>1</td>\n      <td>0</td>\n      <td>5.53</td>\n      <td>28</td>\n      <td>1.77</td>\n      <td>27.2</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Chase Burns</td>\n      <td>Starter</td>\n      <td>11</td>\n      <td>1</td>\n      <td>2.54</td>\n      <td>118</td>\n      <td>1.11</td>\n      <td>102.2</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>Andrew Abbott</td>\n      <td>Starter</td>\n      <td>5</td>\n      <td>5</td>\n      <td>4.11</td>\n      <td>84</td>\n      <td>1.42</td>\n      <td>105.0</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>Nick Lodolo</td>\n      <td>Starter</td>\n      <td>3</td>\n      <td>2</td>\n      <td>4.60</td>\n      <td>50</td>\n      <td>1.47</td>\n      <td>62.2</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>Brady Singer</td>\n      <td>Starter</td>\n      <td>3</td>\n      <td>9</td>\n      <td>4.72</td>\n      <td>76</td>\n      <td>1.47</td>\n      <td>89.2</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>Rhett Lowder</td>\n      <td>Starter</td>\n      <td>3</td>\n      <td>6</td>\n      <td>4.91</td>\n      <td>59</td>\n      <td>1.54</td>\n      <td>69.2</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>Brandon Williamson</td>\n      <td>Starter</td>\n      <td>2</td>\n      <td>3</td>\n      <td>6.11</td>\n      <td>19</td>\n      <td>1.64</td>\n      <td>28.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nSplitting by role clarifies who is actually holding the staff together.\nAmong starters, Chase Burns is the headline: an 11-1 record and a 2.54\nERA over 102.2 innings, averaging just under 95 mph with plus spin on\nhis fastball, the profile of a legitimate front-of-rotation arm rather\nthan a first-half surprise. Among relievers, Tejay Antone's 2.25 ERA is\nthe clear standout. Beyond those two, both groups thin out quickly.\n\nThe same early-vs-recent split used earlier in this post, applied to\nthe Reds staff specifically, shows why that thinness matters more than\nany single number in the season table above.\n\n::: {#cell-fetch-reds-pitching-trend .cell execution_count=18}\n``` {.python .cell-code}\nreds_pitch_trend_query = \"\"\"\nWITH pa AS (\n  SELECT\n    pitcher,\n    CAST(game_date AS DATE) AS game_date,\n    woba_value, woba_denom\n  FROM `maydaystats.mlb_statcast.pitches`\n  WHERE game_type = 'R' AND woba_denom IS NOT NULL\n),\nmax_date AS (SELECT MAX(game_date) AS d FROM pa),\nsplits AS (\n  SELECT\n    pitcher,\n    SUM(IF(game_date < DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), woba_value, 0)) AS early_val,\n    SUM(IF(game_date < DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), woba_denom, 0)) AS early_bf,\n    SUM(IF(game_date >= DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), woba_value, 0)) AS recent_val,\n    SUM(IF(game_date >= DATE_SUB((SELECT d FROM max_date), INTERVAL 45 DAY), woba_denom, 0)) AS recent_bf\n  FROM pa\n  GROUP BY pitcher\n)\nSELECT\n  p.player_name,\n  IF(SAFE_DIVIDE(p.gamesStarted, p.gamesPitched) >= 0.5, 'Starter', 'Reliever') AS role,\n  ROUND(SAFE_DIVIDE(s.early_val, s.early_bf), 3) AS early_woba_against,\n  ROUND(SAFE_DIVIDE(s.recent_val, s.recent_bf), 3) AS recent_woba_against\nFROM splits s\nJOIN `maydaystats.mlb_season_stats.pitching_latest` p ON p.player_id = s.pitcher\nWHERE p.team_name = 'Cincinnati Reds' AND s.early_bf >= 20 AND s.recent_bf >= 20\nORDER BY role, recent_woba_against ASC\n\"\"\"\nreds_pitch_trend = client.query(reds_pitch_trend_query).to_dataframe()\nreds_pitch_trend_tbl = reds_pitch_trend.reset_index(drop=True)\nreds_pitch_trend_tbl.index += 1\nreds_pitch_trend_tbl\n```\n\n::: {#fetch-reds-pitching-trend .cell-output .cell-output-display execution_count=18}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>player_name</th>\n      <th>role</th>\n      <th>early_woba_against</th>\n      <th>recent_woba_against</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>Tejay Antone</td>\n      <td>Reliever</td>\n      <td>0.328</td>\n      <td>0.279</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Tony Santillan</td>\n      <td>Reliever</td>\n      <td>0.397</td>\n      <td>0.300</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Chase Petty</td>\n      <td>Reliever</td>\n      <td>0.334</td>\n      <td>0.313</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Brock Burke</td>\n      <td>Reliever</td>\n      <td>0.352</td>\n      <td>0.318</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Pierce Johnson</td>\n      <td>Reliever</td>\n      <td>0.322</td>\n      <td>0.408</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Sam Moll</td>\n      <td>Reliever</td>\n      <td>0.293</td>\n      <td>0.432</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Chase Burns</td>\n      <td>Starter</td>\n      <td>0.267</td>\n      <td>0.330</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Brady Singer</td>\n      <td>Starter</td>\n      <td>0.428</td>\n      <td>0.331</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Andrew Abbott</td>\n      <td>Starter</td>\n      <td>0.331</td>\n      <td>0.333</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>Nick Lodolo</td>\n      <td>Starter</td>\n      <td>0.404</td>\n      <td>0.346</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>Rhett Lowder</td>\n      <td>Starter</td>\n      <td>0.321</td>\n      <td>0.383</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nIt's a mixed picture, not a uniform one. Tejay Antone and Brady Singer\nhave both gotten better against opposing hitters recently, and Andrew\nAbbott has held steady. Chase Burns has actually seen his opponent wOBA\nrise somewhat over the last 45 days, still solid, just not quite as\ndominant as his season line suggests. The clearer problem is further\ndown the staff: Rhett Lowder and Sam Moll have both gotten meaningfully\nworse against opposing hitters recently, and neither was especially\nstrong to begin with. A rotation and bullpen this dependent on two\npitchers performing at their best has less margin for error than a\nstaff with the same season-long ERA spread more evenly.\n\nPut together, the Reds' first half looks less like a team that fell\napart and more like a team that was already below average on offense,\ngot worse there over the last 45 days, and has real pitching depth\nquestions once you get past Burns and Antone. The individual talent is\nreal (De La Cruz, Burns, Antone), and a couple of hitters, Hayes\nespecially, look likely to see their results catch up to their contact\nquality. Whether that's enough to climb out of last place in the NL\nCentral is a second-half question, but it will take more than better\nluck; the offense needs to actually produce more runs than it has all\nyear, not just more than its recent stretch.\n\n::: {.callout-note}\nThis post uses Quarto's frozen execution (`freeze: auto`): the numbers\nabove reflect the Statcast and `mlb_season_stats` data as of whenever\nthis was last rendered locally, not a live query on every page load.\n\"Last 45 days\" is calculated relative to the most recent game date in\nthe pipeline at render time, not a fixed calendar date.\n:::\n\n",
    "supporting": [
      "index_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}